insert into weathers (id, pref, area, latitude, longitude, url, xpath) values (0, '北海道', '上川地方', 43.6155, 142.8410, 'http://www.drk7.jp/weather/xml/01.xml', 'weatherforecast/pref/area[1]'),
insert into weathers (id, pref, area, latitude, longitude, url, xpath) values (1, '北海道', '北見地方', 43.8061, 143.4782, 'http://www.drk7.jp/weather/xml/01.xml', 'weatherforecast/pref/area[2]'),
insert into weathers (id, pref, area, latitude, longitude, url, xpath) values (2, '北海道', '十勝地方', 42.7260, 143.4453, 'http://www.drk7.jp/weather/xml/01.xml', 'weatherforecast/pref/area[3]'),
insert into weathers (id, pref, area, latitude, longitude, url, xpath) values (3, '北海道', '宗谷地方', 45.3708, 141.7094, 'http://www.drk7.jp/weather/xml/01.xml', 'weatherforecast/pref/area[4]'),
insert into weathers (id, pref, area, latitude, longitude, url, xpath) values (4, '北海道', '後志地方', 42.9516, 140.7097, 'http://www.drk7.jp/weather/xml/01.xml', 'weatherforecast/pref/area[5]'),
insert into weathers (id, pref, area, latitude, longitude, url, xpath) values (5, '北海道', '日高地方', 42.2399, 142.7531, 'http://www.drk7.jp/weather/xml/01.xml', 'weatherforecast/pref/area[6]'),
insert into weathers (id, pref, area, latitude, longitude, url, xpath) values (6, '北海道', '根室地方', 43.2724, 145.4448, 'http://www.drk7.jp/weather/xml/01.xml', 'weatherforecast/pref/area[7]'),
insert into weathers (id, pref, area, latitude, longitude, url, xpath) values (7, '北海道', '檜山地方', 42.8892,
140.1604, 'http://www.drk7.jp/weather/xml/01.xml', 'weatherforecast/pref/area[8]'),
insert into weathers (id, pref, area, latitude, longitude, url, xpath) values (8, '北海道', '渡島地方', 42.8073, 140.7317, 'http://www.drk7.jp/weather/xml/01.xml', 'weatherforecast/pref/area[9]'),
insert into weathers (id, pref, area, latitude, longitude, url, xpath) values (9, '北海道', '留萌地方', 44.9486, 
141.6545, 'http://www.drk7.jp/weather/xml/01.xml', 'weatherforecast/pref/area[10]'),
insert into weathers (id, pref, area, latitude, longitude, url, xpath) values (10, '北海道', '石狩地方', 43.0801, 141.3469, 'http://www.drk7.jp/weather/xml/01.xml', 'weatherforecast/pref/area[11]'),
insert into weathers (id, pref, area, latitude, longitude, url, xpath) values (11, '北海道', '空知地方', 43.4242, 141.9621, 'http://www.drk7.jp/weather/xml/01.xml', 'weatherforecast/pref/area[12]'),
insert into weathers (id, pref, area, latitude, longitude, url, xpath) values (12, '北海道', '紋別地方', 44.3507, 143.3025, 'http://www.drk7.jp/weather/xml/01.xml', 'weatherforecast/pref/area[13]'),
insert into weathers (id, pref, area, latitude, longitude, url, xpath) values (13, '北海道', '綱走地方', 44.0277, 144.2253, 'http://www.drk7.jp/weather/xml/01.xml', 'weatherforecast/pref/area[14]'),
insert into weathers (id, pref, area, latitude, longitude, url, xpath) values (14, '北海道', '胆振地方', 42.3861, 140.9843, 'http://www.drk7.jp/weather/xml/01.xml', 'weatherforecast/pref/area[15]'),
insert into weathers (id, pref, area, latitude, longitude, url, xpath) values (15, '北海道', '釧路地方', 44.2406, 144.6208, 'http://www.drk7.jp/weather/xml/01.xml', 'weatherforecast/pref/area[16]');
